[ { 'application_year': 2023,
    'fpl': 24860,
    'household_id': 1,
    'household_size': 3,
    'persons': [ { 'age': 45,
                   'claimed_dependent': False,
                   'dob': 283798018,
                   'former_foster_care': False,
                   'has_abd_status': False,
                   'has_insurance': False,
                   'income_distribution': [ { 'amount': 0,
                                              'type': 'monthly_income'},
                                            { 'amount': 36543.2,
                                              'type': 'wages_salary_tips'},
                                            { 'amount': 0,
                                              'type': 'taxable_interest'},
                                            { 'amount': 0,
                                              'type': 'tax_exempt_interest'},
                                            { 'amount': 0,
                                              'type': 'tax_refunds_credits_offsets'},
                                            {'amount': 0, 'type': 'alimony'},
                                            { 'amount': 0,
                                              'type': 'capital_gain_or_loss'},
                                            { 'amount': 0,
                                              'type': 'pensions_annuities'},
                                            { 'amount': 0,
                                              'type': 'farm_income_or_loss'},
                                            { 'amount': 0,
                                              'type': 'unemployment_compensation'},
                                            { 'amount': 0,
                                              'type': 'other_income'},
                                            { 'amount': 0,
                                              'type': 'magi_deductions'}],
                   'is_applicant': True,
                   'is_citizen': True,
                   'is_incarcerated': False,
                   'is_medicare_eligible': False,
                   'is_post_partum': False,
                   'is_pregnant': False,
                   'is_student': False,
                   'lives_in_state': True,
                   'long_term_care': False,
                   'must_file_taxes': False,
                   'person_id': 1,
                   'prior_insurance': False,
                   'relationships': [ { 'attests_responsibility': False,
                                        'person_id': 2,
                                        'relationship_code': 3},
                                      { 'attests_responsibility': False,
                                        'person_id': 3,
                                        'relationship_code': 3}],
                   'state_health_benefits': False,
                   'weekly_work_hours': 0},
                 { 'age': 9,
                   'claimed_dependent': False,
                   'dob': 1419871618,
                   'former_foster_care': False,
                   'has_abd_status': False,
                   'has_insurance': False,
                   'income_distribution': [ { 'amount': 0,
                                              'type': 'monthly_income'},
                                            { 'amount': 0,
                                              'type': 'wages_salary_tips'},
                                            { 'amount': 0,
                                              'type': 'taxable_interest'},
                                            { 'amount': 0,
                                              'type': 'tax_exempt_interest'},
                                            { 'amount': 0,
                                              'type': 'tax_refunds_credits_offsets'},
                                            {'amount': 0, 'type': 'alimony'},
                                            { 'amount': 0,
                                              'type': 'capital_gain_or_loss'},
                                            { 'amount': 0,
                                              'type': 'pensions_annuities'},
                                            { 'amount': 0,
                                              'type': 'farm_income_or_loss'},
                                            { 'amount': 0,
                                              'type': 'unemployment_compensation'},
                                            { 'amount': 0,
                                              'type': 'other_income'},
                                            { 'amount': 0,
                                              'type': 'magi_deductions'}],
                   'is_applicant': True,
                   'is_citizen': True,
                   'is_incarcerated': False,
                   'is_medicare_eligible': False,
                   'is_post_partum': False,
                   'is_pregnant': False,
                   'is_student': False,
                   'lives_in_state': True,
                   'long_term_care': False,
                   'must_file_taxes': False,
                   'person_id': 2,
                   'prior_insurance': False,
                   'relationships': [ { 'attests_responsibility': False,
                                        'person_id': 1,
                                        'relationship_code': 4},
                                      { 'attests_responsibility': False,
                                        'person_id': 3,
                                        'relationship_code': 7}],
                   'state_health_benefits': False,
                   'weekly_work_hours': 0},
                 { 'age': 7,
                   'claimed_dependent': False,
                   'dob': 1483030018,
                   'former_foster_care': False,
                   'has_abd_status': False,
                   'has_insurance': False,
                   'income_distribution': [ { 'amount': 0,
                                              'type': 'monthly_income'},
                                            { 'amount': 0,
                                              'type': 'wages_salary_tips'},
                                            { 'amount': 0,
                                              'type': 'taxable_interest'},
                                            { 'amount': 0,
                                              'type': 'tax_exempt_interest'},
                                            { 'amount': 0,
                                              'type': 'tax_refunds_credits_offsets'},
                                            {'amount': 0, 'type': 'alimony'},
                                            { 'amount': 0,
                                              'type': 'capital_gain_or_loss'},
                                            { 'amount': 0,
                                              'type': 'pensions_annuities'},
                                            { 'amount': 0,
                                              'type': 'farm_income_or_loss'},
                                            { 'amount': 0,
                                              'type': 'unemployment_compensation'},
                                            { 'amount': 0,
                                              'type': 'other_income'},
                                            { 'amount': 0,
                                              'type': 'magi_deductions'}],
                   'is_applicant': True,
                   'is_citizen': True,
                   'is_incarcerated': False,
                   'is_medicare_eligible': False,
                   'is_post_partum': False,
                   'is_pregnant': False,
                   'is_student': False,
                   'lives_in_state': True,
                   'long_term_care': False,
                   'must_file_taxes': False,
                   'person_id': 3,
                   'prior_insurance': False,
                   'relationships': [ { 'attests_responsibility': False,
                                        'person_id': 1,
                                        'relationship_code': 4},
                                      { 'attests_responsibility': False,
                                        'person_id': 2,
                                        'relationship_code': 7}],
                   'state_health_benefits': False,
                   'weekly_work_hours': 0}]}]
