[ { 'fpl': 24860,
    'household_id': 1,
    'household_size': 3,
    'persons': [ { 'age': 45,
                   'claimed_dependent': False,
                   'dob': 283792403,
                   'former_foster_care': False,
                   'has_abd_status': False,
                   'has_insurance': False,
                   'income_distribution': [ 0,
                                            36543.2,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0],
                   'is_applicant': True,
                   'is_citizen': True,
                   'is_incarcerated': False,
                   'is_medicare_eligible': False,
                   'is_post_partum': False,
                   'is_pregnant': False,
                   'is_student': False,
                   'lives_in_state': True,
                   'long_term_care': False,
                   'must_file_taxes': False,
                   'person_id': 1,
                   'prior_insurance': False,
                   'relationships': [ { 'attests_responsibility': False,
                                        'person_id': 2,
                                        'relationship_code': 3},
                                      { 'attests_responsibility': False,
                                        'person_id': 3,
                                        'relationship_code': 3}],
                   'state_health_benefits': False,
                   'weekly_work_hours': 0},
                 { 'age': 9,
                   'claimed_dependent': False,
                   'dob': 1419866003,
                   'former_foster_care': False,
                   'has_abd_status': False,
                   'has_insurance': False,
                   'income_distribution': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   'is_applicant': True,
                   'is_citizen': True,
                   'is_incarcerated': False,
                   'is_medicare_eligible': False,
                   'is_post_partum': False,
                   'is_pregnant': False,
                   'is_student': False,
                   'lives_in_state': True,
                   'long_term_care': False,
                   'must_file_taxes': False,
                   'person_id': 2,
                   'prior_insurance': False,
                   'relationships': [ { 'attests_responsibility': False,
                                        'person_id': 1,
                                        'relationship_code': 4},
                                      { 'attests_responsibility': False,
                                        'person_id': 3,
                                        'relationship_code': 7}],
                   'state_health_benefits': False,
                   'weekly_work_hours': 0},
                 { 'age': 7,
                   'claimed_dependent': False,
                   'dob': 1483024403,
                   'former_foster_care': False,
                   'has_abd_status': False,
                   'has_insurance': False,
                   'income_distribution': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   'is_applicant': True,
                   'is_citizen': True,
                   'is_incarcerated': False,
                   'is_medicare_eligible': False,
                   'is_post_partum': False,
                   'is_pregnant': False,
                   'is_student': False,
                   'lives_in_state': True,
                   'long_term_care': False,
                   'must_file_taxes': False,
                   'person_id': 3,
                   'prior_insurance': False,
                   'relationships': [ { 'attests_responsibility': False,
                                        'person_id': 1,
                                        'relationship_code': 4},
                                      { 'attests_responsibility': False,
                                        'person_id': 2,
                                        'relationship_code': 7}],
                   'state_health_benefits': False,
                   'weekly_work_hours': 0}]}]
