{ 'Application Year': 2021,
  'Name': 'Frontend Application',
  'People': [ { 'Applicant Age': 45,
                'Applicant Age >= 90': 'N',
                'Applicant Attest Blind or Disabled': 'N',
                'Applicant Attest Long Term Care': 'N',
                'Applicant Post Partum Period Indicator': 'N',
                'Applicant Pregnant Indicator': 'N',
                'Claimed as Dependent by Person Not on Application': 'N',
                'Former Foster Care': 'N',
                'Has Insurance': 'N',
                'Hours Worked Per Week': 0,
                'Incarceration Status': 'N',
                'Income': { 'Alimony': 0,
                            'Capital Gain or Loss': 0,
                            'Farm Income or Loss': 0,
                            'MAGI Deductions': 0,
                            'Monthly Income': 0,
                            'Other Income': 0,
                            'Pensions and Annuities Taxable Amount': 0,
                            'Tax-Exempt Interest': 0,
                            'Taxable Interest': 0,
                            'Taxable Refunds, Credits, or Offsets of State and Local Income Taxes': 0,
                            'Unemployment Compensation': 0,
                            'Wages, Salaries, Tips': 0},
                'Is Applicant': 'Y',
                'Lives In State': 'Y',
                'Medicare Entitlement Indicator': 'N',
                'Person ID': 1,
                'Prior Insurance': 'N',
                'Relationships': [ { 'Attest Primary Responsibility': 'N',
                                     'Other ID': 2,
                                     'Relationship Code': '03'},
                                   { 'Attest Primary Responsibility': 'N',
                                     'Other ID': 3,
                                     'Relationship Code': '03'}],
                'Required to File Taxes': 'N',
                'State Health Benefits Through Public Employee': 'N',
                'Student Indicator': 'N',
                'US Citizen Indicator': 'Y'},
              { 'Applicant Age': 9,
                'Applicant Age >= 90': 'N',
                'Applicant Attest Blind or Disabled': 'N',
                'Applicant Attest Long Term Care': 'N',
                'Applicant Post Partum Period Indicator': 'N',
                'Applicant Pregnant Indicator': 'N',
                'Claimed as Dependent by Person Not on Application': 'N',
                'Former Foster Care': 'N',
                'Has Insurance': 'N',
                'Hours Worked Per Week': 0,
                'Incarceration Status': 'N',
                'Income': { 'Alimony': 0,
                            'Capital Gain or Loss': 0,
                            'Farm Income or Loss': 0,
                            'MAGI Deductions': 0,
                            'Monthly Income': 0,
                            'Other Income': 0,
                            'Pensions and Annuities Taxable Amount': 0,
                            'Tax-Exempt Interest': 0,
                            'Taxable Interest': 0,
                            'Taxable Refunds, Credits, or Offsets of State and Local Income Taxes': 0,
                            'Unemployment Compensation': 0,
                            'Wages, Salaries, Tips': 0},
                'Is Applicant': 'Y',
                'Lives In State': 'Y',
                'Medicare Entitlement Indicator': 'N',
                'Person ID': 2,
                'Prior Insurance': 'N',
                'Relationships': [ { 'Attest Primary Responsibility': 'N',
                                     'Other ID': 1,
                                     'Relationship Code': '04'},
                                   { 'Attest Primary Responsibility': 'N',
                                     'Other ID': 3,
                                     'Relationship Code': '07'}],
                'Required to File Taxes': 'N',
                'State Health Benefits Through Public Employee': 'N',
                'Student Indicator': 'N',
                'US Citizen Indicator': 'Y'},
              { 'Applicant Age': 7,
                'Applicant Age >= 90': 'N',
                'Applicant Attest Blind or Disabled': 'N',
                'Applicant Attest Long Term Care': 'N',
                'Applicant Post Partum Period Indicator': 'N',
                'Applicant Pregnant Indicator': 'N',
                'Claimed as Dependent by Person Not on Application': 'N',
                'Former Foster Care': 'N',
                'Has Insurance': 'N',
                'Hours Worked Per Week': 0,
                'Incarceration Status': 'N',
                'Income': { 'Alimony': 0,
                            'Capital Gain or Loss': 0,
                            'Farm Income or Loss': 0,
                            'MAGI Deductions': 0,
                            'Monthly Income': 0,
                            'Other Income': 0,
                            'Pensions and Annuities Taxable Amount': 0,
                            'Tax-Exempt Interest': 0,
                            'Taxable Interest': 0,
                            'Taxable Refunds, Credits, or Offsets of State and Local Income Taxes': 0,
                            'Unemployment Compensation': 0,
                            'Wages, Salaries, Tips': 0},
                'Is Applicant': 'Y',
                'Lives In State': 'Y',
                'Medicare Entitlement Indicator': 'N',
                'Person ID': 3,
                'Prior Insurance': 'N',
                'Relationships': [ { 'Attest Primary Responsibility': 'N',
                                     'Other ID': 1,
                                     'Relationship Code': '04'},
                                   { 'Attest Primary Responsibility': 'N',
                                     'Other ID': 2,
                                     'Relationship Code': '07'}],
                'Required to File Taxes': 'N',
                'State Health Benefits Through Public Employee': 'N',
                'Student Indicator': 'N',
                'US Citizen Indicator': 'Y'}],
  'Physical Households': [ { 'Household ID': 'Household1',
                             'People': [ {'Person ID': 1},
                                         {'Person ID': 2},
                                         {'Person ID': 3}]}],
  'State': 'NJ',
  'Tax Returns': [{'Dependents': [], 'Filers': []}]}
